version: 2
jobs:
  build:

    docker:
    - image: circleci/node:8.4
  
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Download Node modules
          command: npm install


      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      
      - run:
          name: Run tests
          command: JEST_JUNIT_OUTPUT=test-reports/junit.xml npm run test:ci

      - run:
          name: Create production build
          command: |
            npm run build
            pushd build
            zip -9vr ./hyperion-web.zip .
            popd
      
      - store_test_results:
          path: "./test-reports/"
      - store_artifacts:
          destination: "test-reports/unit-test"
          path: "./test-reports/"
      - store_artifacts:
          destination: "packages/zip/"
          path: "build/hyperion-web.zip"
